x_key: 'x'
y_key: 'y'

# metadata specialised for each experiment
core:
  project_name: modelzoo
  storage_dir: ${oc.env:PROJECT_ROOT}/storage
  version: 0.0.1
  name: null
  tags:
  - develop

defaults:
  - hydra: default
  - nn: default
  - train: default
  - _self_ # as last argument to allow the override of parameters via this main config
#    Decomment this parameter to get parallel job running
#  - hydra/launcher: joblib
