_target_: modelzoo.modules.aes.ae.VanillaAE

relative_projection_config:
  _target_: modelzoo.relative.projection.RelativeBlock
  projection_names:
    - Cosine
    - Euclidean
    - L1
    - Linf
  aggregation_module:
    _target_: modelzoo.relative.aggregation.NonLinearSumAggregation
    subspace_dim: ${nn.data.anchors_num}
    num_subspaces: 4

encoder_layers_config:
  - _target_: anypy.nn.dyncnn.infer_convolution2d
    input_shape: ???
    output_shape: [-1, 32, 28, 28]
    kernel_size: null
    stride: 1
    padding: 0
    dilation: 1
  - _target_: torch.nn.ReLU
  - _target_: torch.nn.BatchNorm2d
    num_features: 32
  - _target_: anypy.nn.dyncnn.infer_convolution2d
    input_shape: ???
    output_shape: [-1, 32, 14, 14]
    kernel_size: 4
    stride: 2
    padding: null
    dilation: 1
  - _target_: torch.nn.ReLU
  - _target_: anypy.nn.dyncnn.infer_convolution2d
    input_shape: ???
    output_shape: [-1, 16, 7, 7]
    kernel_size: null
    stride: 2
    padding: 1
    dilation: 1
  - _target_: torch.nn.ReLU
  - _target_: torch.nn.BatchNorm2d
    num_features: 16

encoder_out_config:
  _target_: torch.nn.Sequential
  _args_:
    - _target_: torch.nn.Flatten
      start_dim: 1
    - _target_: torch.nn.Linear
      in_features: 784
      out_features: 784

decoder_in_config:
  _target_: torch.nn.Sequential
  _args_:
    - _target_: torch.nn.LayerNorm
      normalized_shape: 784
    - _target_: torch.nn.Linear
      in_features: 784
      out_features: 784
    - _target_: torch.nn.Unflatten
      dim: 1
      unflattened_size: [16, 7, 7]

decoder_layers_config:
  - _target_: anypy.nn.dyncnn.infer_transposed_convolution2d
    input_shape: ???
    output_shape: [-1, 32, 14, 14]
    kernel_size: null
    stride: 2
    padding: 1
    dilation: 1
  - _target_: torch.nn.ReLU
  - _target_: torch.nn.BatchNorm2d
    num_features: 32
  - _target_: anypy.nn.dyncnn.infer_transposed_convolution2d
    input_shape: ???
    output_shape: [-1, 32, 28, 28]
    kernel_size: null
    stride: 2
    padding: 1
    dilation: 1
  - _target_: torch.nn.ReLU
  - _target_: torch.nn.BatchNorm2d
    num_features: 32
  - _target_: anypy.nn.dyncnn.infer_transposed_convolution2d
    input_shape: ???
    output_shape: ???
    kernel_size: null
    stride: 1
    padding: 1
    dilation: 1
  - _target_: torch.nn.Sigmoid
