_target_: modelzoo.modules.aes.vae.VanillaVAE
latent_dim: 128
hidden_dims: [8, 16, 16, 32, 64]
calibrated_loss: False
kld_weight: 0.025
decoder_in_normalization: ???

defaults:
  - decoder_in_normalization: none
