data: ???

module:
  model:
    input_size: ${nn.data.datasets.hf.input_size}
    in_channels: ${nn.data.datasets.hf.in_channels}

  plot_n_val_samples: 1000
  fit_pca_each_epoch: True

  optimizer:
    #  Adam-oriented deep learning
    _target_: torch.optim.Adam
    #  These are all default parameters for the Adam optimizer
    lr: 1e-3
    betas: [ 0.9, 0.999 ]
    eps: 1e-08
    weight_decay: 1e-5

#  lr_scheduler:
#    _target_: torch.optim.lr_scheduler.CosineAnnealingWarmRestarts
#    T_0: 20
#    T_mult: 1
#    eta_min: 0
#    last_epoch: -1
#    verbose: False


defaults:
  - _self_
  - data: default # pick one of the yamls in nn/data/
  - module: autoencoder # ae_variational # classifier #  ae_deterministic #
